export const Userlogin=[
    {
        email:'ad@123gmail.com',
        password:'123',
        username:'Anish123',
        fname:'Anish',
        lname:'Dhar'
    },
    {
        email:'anu@456gmail.com',
        password:'321',
        username:'Sws202',
        fname:'Swastika',
        lname:'Roy'
    },
    {
        email:'sar@678gmail.com',
        password:'222',
        username:'Riya432',
        fname:'Riya',
        lname:'Deb'
    },
    {
        email:'cs@999gmail.com',
        password:'333',
        username:'Nilu456',
        fname:'Niladri',
        lname:'Debnath'
    },
    {
        email:'bw@000gmail.com',
        password:'555',
        username:'Apu321',
        fname:'Apu',
        lname:'Karmakar'
    },
]